### ISSUE TITLE
Upload progress data to Frogress

### ISSUE THREAD

**Issue by laqieer** [StanHash/fe6#11]
I made it for [fe8 decomp](https://github.com/FireEmblemUniverse/fireemblem8u), and [this is the website](https://laqieer.github.io/fe-decomp-portal/). I would like to add fe6 to it too. Would you mind sharing the data?

If you don't mind it, do you prefer doing it by yourself or entrusting me to do it?

- If you prefer the former, I wrote a [guide](https://github.com/decompals/frogress/blob/main/GUIDE.md) for you to follow, and I suggest to keep the same category and metrics with me so that I needn't modify my React component to reuse it.
- If you prefer the latter, you only need to input Frogress API key at last following the guide in this PR: https://github.com/FireEmblemUniverse/fireemblem8u/pull/307

**Comment by StanHash** [comment]
This would be neat. I would like to set this up myself, and I would want to take the time to do this properly.

I'll make you know when I'll have the data ready.

**Comment by StanHash** [comment]
https://progress.deco.mp/data/fireemblem6/jp/default/ @laqieer there you go!

It is formatted like fe8 except there's no `data/banim` metric (it breaks the "data" line on the graph in your app sorry; a simple fix would be to assume it is 0 if not present) (there is also no `functions/unmatched` but I believe your app doesn't care for it anyway)

**Comment by laqieer** [comment]
Done. Thanks for your collaboration!
